---
title: "KEVIN W. GILDS, MPA"
output:
  pdf_document: default
  word_document: default
  html_document:
    keep_md: yes
---


-------------------     ----------------------------
863-399-4362                        
Lakeland, Florida        kgilds@rbind.com
MyCountry                
-------------------     ----------------------------

## Expertise in Collecting, Managing, and Analyzing Data



### Skill Summary

Excel/Access|Calculate/Interpret Statistics|R Programming | Git/Github | SQL
-----------| ---|--------------|-----------|--------------|------------|









### Work Experience


DATA SCIENCE


* **Created functions, scripts and reports in R to manage survey and academic data for the Get REAL! statewide mentoring program:** resulting in a work process that is automated and reproducible.

* **Developed Shiny dashboard application to communicate data entry status from multiple site locations** resulting in keeping client updated on data entry progress. 


* **Developed best practices to sanitize data and merge spreadsheets using the Vlookup Function:** Resulting in increased efficiency in meeting performance measures and helping consumers get services faster.

* **Identified data sources and requirements to automate billing process and collaborated with MIS to implement**: resulting in saving 20 hours of data entry and improving efficiency of billing process.     


* **Developed Google Drive Form/Spreadsheet combination to process 800+ referrals a month:** resulting in increasing data quality,  real time reporting of workload, and faster response time to referrals.
   
PROJECT MANAGEMENT

* **Manage program databases and identify needed data to make more effective reports and queries:** resulting in automated reports for management and partners.

* **Led team in managing the process of helping seniors obtain eligibility for Long Term Care Services:** assigned workloads, set milestones, and monitored progress of monthly releases, resulting in achieving performance measures every month over 2 years.

* **Monitored phone calls and staff documentation to ensure quality assurance standards were being met:** resulting in the identification of training needs for staff to help improve communication to consumers.

* **Generate staff productivity reports that measursed staff productivity:** resulting in conversations with teams members about their weekly productivity and providing technical assistance to remove barriers to success.

* **Created videos and written documentation to teach and document technical processes to manage data and workflow:** resulting in delegations of tasks and staff development.



\ 




EDUCATION

* University of South Florida-MPA Public Administration, 2007

* University of Northern Iowa-BA Sociology, 1999

* Kirkwood Community College-AA Legal Assistant, 1998

